<a href="https://colab.research.google.com/github/shreshta97/DATA-690-WANG/blob/master/Assignment_03/Assignment_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment_03 09-13-2020
## 1. Write a program that generates 100 random integers between 0 and 9.

- Print them in a 10 by 10 matrix neatly arranged like the following (one space between each number):

In [1]:
# Import the NUMpy library  
import numpy as np
# Generate a random matrix of 10 by 10 with digits 0-9 using the np.random function 
random_matrix = np.random.randint(0,9,(10,10))
print(random_matrix)

[[5 7 2 4 1 4 7 2 4 2]
 [0 8 7 3 0 1 1 5 4 1]
 [7 4 7 6 6 7 5 1 6 3]
 [4 4 8 2 2 3 1 2 6 3]
 [4 8 8 7 2 7 5 3 2 8]
 [2 1 6 0 7 2 6 5 8 0]
 [8 8 4 7 2 2 7 3 8 7]
 [0 0 0 5 7 3 0 6 0 0]
 [8 6 2 5 3 7 5 4 0 7]
 [5 1 0 5 5 5 0 3 8 1]]


## 2. If the random number is an odd number, print "@" instead: 

In [65]:
# finding all the odd values in the matrix and replacing with -1 as a place holder
odd_values = (random_matrix%2==1) 

random_matrix[odd_values] = -1 

print(random_matrix)

[[-1 -1  0  0 -1 -1  6  6  0  2]
 [ 8  8  0  2 -1  8  4 -1  0  6]
 [-1 -1 -1  2 -1 -1 -1 -1 -1  6]
 [-1  0  8  2  0  8 -1 -1  8  8]
 [ 4 -1 -1  6 -1  2 -1 -1  6  2]
 [ 6 -1  0 -1  6  8 -1  8 -1 -1]
 [ 6  8 -1  4  6  6 -1 -1 -1  4]
 [-1  0  4 -1  6 -1 -1  6  0  8]
 [ 4 -1  4 -1  4  2 -1 -1 -1  6]
 [ 6 -1  6 -1  4 -1  0 -1  0  2]]


In [161]:
# convert all the values in the matrix from integers to strings
random_matrix1= np.char.mod('%d', random_matrix)
print(random_matrix1)

[['7' '3' '6' '4' '0' '1' '5' '3' '6' '2']
 ['0' '6' '6' '4' '3' '2' '6' '5' '7' '5']
 ['4' '4' '6' '7' '3' '3' '4' '4' '6' '6']
 ['1' '5' '2' '4' '1' '4' '3' '2' '5' '8']
 ['0' '0' '1' '4' '2' '4' '7' '8' '6' '5']
 ['4' '6' '2' '5' '0' '0' '1' '2' '2' '3']
 ['4' '3' '5' '4' '1' '3' '6' '6' '3' '6']
 ['6' '4' '2' '7' '3' '3' '4' '4' '0' '7']
 ['6' '7' '7' '4' '0' '1' '4' '6' '7' '3']
 ['2' '3' '1' '3' '3' '6' '3' '2' '2' '4']]


In [166]:
# testing to see if we can replace the digits 
a = np.char.replace(random_matrix1, ('1'), '@')
b = np.char.replace(a,('3'),'@')
c = np.char.replace(b,('5'),'@')
d = np.char.replace(c,('7'),'@')
e = np.char.replace(d,('3'),'@')
print(e)


[['@' '@' '6' '4' '0' '@' '@' '@' '6' '2']
 ['0' '6' '6' '4' '@' '2' '6' '@' '@' '@']
 ['4' '4' '6' '@' '@' '@' '4' '4' '6' '6']
 ['@' '@' '2' '4' '@' '4' '@' '2' '@' '8']
 ['0' '0' '@' '4' '2' '4' '@' '8' '6' '@']
 ['4' '6' '2' '@' '0' '0' '@' '2' '2' '@']
 ['4' '@' '@' '4' '@' '@' '6' '6' '@' '6']
 ['6' '4' '2' '@' '@' '@' '4' '4' '0' '@']
 ['6' '@' '@' '4' '0' '@' '4' '6' '@' '@']
 ['2' '@' '@' '@' '@' '6' '@' '2' '2' '4']]


# 3. Calculate and Print the total of each row (use "*" to separate the total from the numbers):

In [183]:
random_sums= np.sum(random_matrix,axis=1)
print(random_sums)


[37 44 47 35 37 25 41 40 45 29]


In [230]:
# not sure why this is happening??
random_sums= np.sum(random_matrix,axis=1)
print(random_sums)
for x in random_sums: 
  if x>0:
    continue

for digit in random_matrix: 
    print(digit,'*', x)

[37 44 47 35 37 25 41 40 45 29]
[7 3 6 4 0 1 5 3 6 2] * 29
[0 6 6 4 3 2 6 5 7 5] * 29
[4 4 6 7 3 3 4 4 6 6] * 29
[1 5 2 4 1 4 3 2 5 8] * 29
[0 0 1 4 2 4 7 8 6 5] * 29
[4 6 2 5 0 0 1 2 2 3] * 29
[4 3 5 4 1 3 6 6 3 6] * 29
[6 4 2 7 3 3 4 4 0 7] * 29
[6 7 7 4 0 1 4 6 7 3] * 29
[2 3 1 3 3 6 3 2 2 4] * 29


In [215]:
# was able to concatenate the random integer matrix with the sums of each row 
## still need to figure out how to add in the *
np.column_stack((random_matrix, random_sums))

array([[ 7,  3,  6,  4,  0,  1,  5,  3,  6,  2, 37],
       [ 0,  6,  6,  4,  3,  2,  6,  5,  7,  5, 44],
       [ 4,  4,  6,  7,  3,  3,  4,  4,  6,  6, 47],
       [ 1,  5,  2,  4,  1,  4,  3,  2,  5,  8, 35],
       [ 0,  0,  1,  4,  2,  4,  7,  8,  6,  5, 37],
       [ 4,  6,  2,  5,  0,  0,  1,  2,  2,  3, 25],
       [ 4,  3,  5,  4,  1,  3,  6,  6,  3,  6, 41],
       [ 6,  4,  2,  7,  3,  3,  4,  4,  0,  7, 40],
       [ 6,  7,  7,  4,  0,  1,  4,  6,  7,  3, 45],
       [ 2,  3,  1,  3,  3,  6,  3,  2,  2,  4, 29]])